### ISSUE TITLE
LaB_4

### ISSUE THREAD

**Issue by Olehonopriichuk** [Olehonopriichuk/LaB_4#1]
План заняття
Створити команду з декількох виконавців (це ваші співавтори з попереднього практичного заняття, команду в журналі виділено кольором), домовитись, над яким репозиторієм буде працювати команда цього разу.

**Comment by Olehonopriichuk** [comment]
> План заняття
> Створити команду з декількох виконавців (це ваші співавтори з попереднього практичного заняття, команду в журналі виділено кольором), домовитись, над яким репозиторієм буде працювати команда цього разу.

**Comment by OlehSkakun** [comment]
План заняття
Створити команду з декількох виконавців (це ваші співавтори з попереднього практичного заняття, команду в журналі виділено кольором), домовитись, над яким репозиторієм буде працювати команда цього разу.
