### ISSUE TITLE
Лабораторна №4

### ISSUE THREAD

**Issue by OlehSkakun** [Olehonopriichuk/LaB_4#2]
Технічна частина
Кожен з пунктів проекту вважається виконаним, якщо до сховища завантажено відповідний файл. Наприклад:
зображення маршруту на карті
текстовий документ з описом пам’яток і цікавих місць пункту подорожі
адреса сайту, знімок екрана з сайтом, де можна забронювати житло
інформація про заклад харчування: адреса в інтернеті та на місцевості, меню, ціни, фото закладу
перелік товарів, які необхідно придбати для подорожі
електронна таблиця з розрахунками кошторису
Звичайно, для виконання проекту не потрібно робити справжні покупки чи бронювання. Достатньо зібрати інформацію, де це можна зробити, і скільки воно буде коштувати.

**Comment by Olehonopriichuk** [comment]
План заняття
Створити команду з декількох виконавців (це ваші співавтори з попереднього практичного заняття, команду в журналі виділено кольором), домовитись, над яким репозиторієм буде працювати команда цього разу.
Увійти в обліковий запис на github.com, отримати доступ до репозиторію:
Власник репозиторію повинен запросити інших членів команди до співавторства: Settings(сховища)/Collaborators (1 на рисунку вгорі).
Інші члени команди повинні прийняти запрошення (перевірити поштову скриньку, повідомлення githhub).
Нагадаємо, що для отримання повідомлень github, потрібно увімкнути їх отримання на Settings(користувача)/Notification → 
Потренувати створення теми для обговорення та власне самого обговорення (Issues, 2 на рисунку вгорі).
Додати позначку, або декілька.
Призначити відповідального.
Створити віху (етап) та приписати до неї обговорення.
Можна використати путівник https://guides.github.com/features/issues/ 
Потренувати створення проекту (Projects, 3 на рисунку вгорі)
Використати автоматизований шаблон
Додати відкриту тему до проекту, завершити обговорення (закрити тему), прослідкувати за її переміщенням у проекті.
Використати шаблон без автоматизації, налаштувати автоматизацію вручну, випробувати додавання та переміщення колонок, додавання записок до колонок та їхнє переміщення.

**Comment by Olehonopriichuk** [comment]
Вистачить тренувань! Тепер справжня робота:
Створіть проект, що відслідковуватиме виконання завдання цього практичного, зробіть його автоматизованим.
Кожен член команди повинен сформулювати як Issue одну-дві пропозиції щодо розширення, покращення сховища, наділити її позначкою (чи декількома), віднести до певного етапу (віхи) та приєднати до створеного проекту.
Пропозиція: додати файл, створити файл, додати таблицю, зображення тощо
Додати файл - для чого, як це покращить проект
Інші члени команди публікують коментарі до пропозицій, призначають відповідальних за виконання.
Етапів у проекті має бути хоча б два.
Для виконання завдань члени команди створюють відгалуження, виконують commits & pull requests.
У назвах до комітів та запитів на злиття використайте “чарівні слова” для автоматичного закривання issue, використовуйте посилання на імена виконавців у коментарях.
Cлідкуйте за прогресом у роботі за індикаторами етапів та на сторінці проекту.
