### ISSUE TITLE
Подорож у Київ!

### ISSUE THREAD

**Issue by Olehonopriichuk** [Olehonopriichuk/LaB_4#4]

**Comment by Olehonopriichuk** [comment]
Який варіан подорожі зручніший? Поїздом чи автівкою?

**Comment by Olehonopriichuk** [comment]
З історії міста

**Comment by Olehonopriichuk** [comment]
•	25 тисячоліття до н. е. — Кирилівська стоянка
•	10 тисячоліття до н. е. — кінець останнього льодовикового періоду
•	4–3 тисячоліття до н. е. — Трипільська культура. У 1893 археолог Вікентій Хвойка відкрив у Києві на вулиці Кирилівській, 55 перше трипільське поселення на території сучасної України
•	II століття до н. е. — II століття Зарубинецька культура, у 1937 році на південній околиці Києва було відкрито Корчуватський могильник
•	I століття — згідно з повістю минулих літ Київські гори відвідав апостол Андрій Первозваний під час своєї місіонерської подорожі до Скіфії і пророкував заснування великого міста на цих горах
•	II століття — створення розвиненого міського поселення на місці сучасного Подолу м. Києва як «Castrum Azagarium» (не пізніше II ст. н. е.).
•	II–V століття — Київська культура
•	III¬–IV століття
•	Черняхівська культура
•	Згадка про країну Оюм, розташовану на території сучасної України, як частину Скіфії, куди переселилися готи, спокусившись на її багатства, згідно з візантійсько-готським істориком Йорданом, на основі старовинних готських саг. Столицею готів було місто Данпарстад (Архаймар). Його точне місцерозташування достеменно невідоме, за однією із версій це могла бути територія сучасного Києва, на користь чого вказує переклад назви Данпарстад, як «Місто на Дніпрі», та розташування біля нього темного (хвойного) лісу Мюрквід
•	IV століття
•	Згідно булгарської хроніки це місто було засноване у 330-х роках н. е. кочівниками у Центральну Європу з Надволжя й Азії, і стародавня булгарська назва цього міста була Башту і Куян (звідки арабські джерела аль–Істархі, Ібн Хордадбех, Ібн-Хаукаль вказували — Куяб, Куйаб етимологічно від «Куб» зі значенням «ім'я Отця Небесного і Бога Сонця, Творця Неба і Землі»[3][4] звідки походять назви Куябія-Куявія-Київ); це місто стояло на холмах (горах), що мали булгарську назву Куян або Кук–Куянтау (тобто «Гори духа Куяна» чи «Кук–Куяна»); перші кагани булгар поховані в цьому місті були Баламбер (Баламир) і Мундзук, котрий передав престіл сину Атилі (Гатило)[5].
•	Згідно з дослідженнями доцента Київського педагогічного інституту Бугая А. С. будівництво оборонних споруд змієвих валів на південних підступах до сучасного Києва[6][7], які частково збереглися. Найближчі до Києва Змієві вали проходять між Дніпром та Ірпенем, по лінії Ходосівка — Хотів — Віта-Поштова — Боярка — Бобриця. Дані А. С. Бугая про вік Змієвих валів базуються на проведених радіовуглецевих аналізах.[8] Змієві вали лишаються однією з найбільших загадок в історії України, вчені не мають одностайної думки про час їх заснування, так академік РАН Борис Рибаков вважав початком їх будівництва X–VIII століття до н.е.[9], а член-кореспондент АН УРСР Артеменко Іван Іванович був зовсім іншої думки і вважав, що будівництво Змієвих валів припадало на кінець Х — початок XI століття н. е.[10]
•	Існує популярна гіпотеза (без переконливих наукових доказів), що князь антів Бож мав резиденцію на Бусовій горі[11], що зараз знаходиться в межах Києва. Бож згадується істориком Йорданом у контексті війни готів з антами. Згідно з Йорданом військо антів спочатку перемогло готів, але у 375 році було розбите, Бож із синами і 70 старійшинами був розіп'ятим для залякування інших антів

**Comment by OlehSkakun** [comment]
Автівкою буде значно краще подорожувати ніж поїздом. Але правильно запаковане авто, має свої переваги. Маю друзів, які всі продукти для подорожі на море, везли з собою з України. Це теж один з варіантів, як подорожувати дешево.
