### ISSUE TITLE
Час подорожі

### ISSUE THREAD

**Issue by Olehonopriichuk** [Olehonopriichuk/LaB_4#5]

**Comment by Olehonopriichuk** [comment]
Скільки часу краще виділити на подорож?

**Comment by OlehSkakun** [comment]
Деякі з ваших ідей спадають на думку тоді, коли ви займаєтесь чимось іншим, окрім вашої роботи. Спробуйте забути про неї під час подорожі і зануртесь в новий досвід, який оточує вас.
