### ISSUE TITLE
Ночівля

### ISSUE THREAD

**Issue by Olehonopriichuk** [Olehonopriichuk/LaB_4#6]

**Comment by Olehonopriichuk** [comment]
Які варіанти для ночівлі запропонуєте?

**Comment by Olehonopriichuk** [comment]
1.	Ночівля:
a.	умови проживання, вартість
Готель. “Готель Нивки”
Кількість зірок. “3”.
Ціна. від 616 грн за 1 ніч для 2 дорослих

b.	можливі варіанти - альтернативні або запасні
      Готель Nyvky Plaza, Готель Фараон, Міні-готель Комфорт.
1.	Харчування (заклади громадського харчування, самостійне приготування):
b.	в дорозі
                 Ресторани, кафе і готелі на трасах.

b. на місці
Хуторець на Дніпрі

**Comment by OlehSkakun** [comment]
Готель "Нивки" найкращий варіант для ночівлі, так як в нього найдешевша ціна за добу.Послуга сніданок в номер. Ціна помірна.
