### ISSUE TITLE
Повернення у Львів

### ISSUE THREAD

**Issue by Olehonopriichuk** [Olehonopriichuk/LaB_4#7]

**Comment by Olehonopriichuk** [comment]
Повертатись у Львів зручніше автобусом чи поїздом? Або ж можливо літаком?

**Comment by OlehSkakun** [comment]
З Києва до Львова курсує два швидкісних експреси Hyundai – один вранці, інший ввечері. Квиток на експрес коштуватиме у першому класі 416 грн (понеділок, субота), 461 грн (вівторок, середа, четвер), 506 грн (п’ятниця і неділя). Ціни у другому класі: 283 грн (понеділок, субота), 313 грн (вівторок, середа і четвер), 343 грн (п’ятниця і неділя). Час в дорозі – близько 5 годин.

Крім того, залізницею курсують звичайні нічні потяги. Наприклад, потяг №141Ш відправляється з Києва о 15:52 і прибуває до Львова о 04:38. Ціна купе - 212 гривень, люкс - 569 гривень, плацкарт - 146 гривень. Він у дорозі понад 12 годин. Ціни на потяг 091 Київ-Львів, що виїжджає о 22:40 і приїжджає о 6:26: купе - 223 гривні, люкс - 525 гривень, плацкарт - 141 гривня. 

Якщо обрати автобусне сполучення, квиток обійдеться дешевше – від 218 до 300 грн. Час в дорозі – від 9 до 11 годин, тобто, практично вдвічі більше, ніж експресом.

Літаком з Києва до Львова можна долетіти рейсами двох авіакомпаній: МАУ та UTair-Ukraine. Вартість квитка – від 1,1 тис. грн до 1,65 тис. грн – залежно від дня тижня. Час в дорозі – від 1 до 1,5 години.

 Якщо їхати автомобілем, то водій ризикує витратити доволі значну суму. Відстань між двома містами – 536 км. Час в дорозі – близько 7,5 години – більше, ніж в експресу. Але вартість дороги може неприємно здивувати – близько 645 грн. Навіть якщо водій їхатиме з одним пасажиром (ціну можна буде поділити на двох), квиток на експрес в другому класі та на автобус – коштуватимуть дешевше.
